/*
    ST7071CEM Information Retrieval Coursework
    Oracle Database Setup Script

    This script creates the custom Oracle tables required for:

        Task 1 - Vertical Search Engine
        Task 2 - Document Clustering

    Django's own framework tables are created separately using:

        python manage.py migrate

    IMPORTANT:
    This script is intended for creating the coursework schema from
    scratch. Do not run the CREATE TABLE statements against an Oracle
    schema where these tables already exist.
*/


/* ============================================================
   TASK 1 - VERTICAL SEARCH ENGINE
   ============================================================ */


/* ------------------------------------------------------------
   VERIFIED CENTRE RESEARCHERS
   ------------------------------------------------------------

   Stores researchers associated with the target Coventry University
   Centre for Healthcare and Community Transformation.
*/

CREATE TABLE RESEARCHERS (

    RESEARCHER_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    NAME VARCHAR2(500)
        NOT NULL,

    PROFILE_URL VARCHAR2(1000)
        NOT NULL
        UNIQUE,

    CENTRE_NAME VARCHAR2(500),

    CRAWLED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* ------------------------------------------------------------
   PUREPORTAL RESEARCH OUTPUTS
   ------------------------------------------------------------

   Stores structured metadata collected from Coventry University's
   official PurePortal research-output pages.

   PUBLICATION_DATE preserves the best publication-date precision
   available from PurePortal, for example:

       May 2026
       05 May 2026

   AUTHOR_PROFILES_JSON stores available PurePortal author-profile
   names and URLs in JSON form.

   SOURCE_NAME and SOURCE_URL preserve provenance information.
*/

CREATE TABLE PUBLICATIONS (

    PUBLICATION_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    TITLE VARCHAR2(1000)
        NOT NULL,

    AUTHORS VARCHAR2(2000),

    PUBLICATION_YEAR NUMBER,

    PUBLICATION_DATE VARCHAR2(50),

    PUBLICATION_URL VARCHAR2(1000)
        NOT NULL
        UNIQUE,

    ABSTRACT CLOB,

    PUBLICATION_TYPE VARCHAR2(100),

    AUTHOR_PROFILES_JSON CLOB,

    SOURCE_NAME VARCHAR2(100),

    SOURCE_URL VARCHAR2(1000),

    CRAWLED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* ------------------------------------------------------------
   PUBLICATION-RESEARCHER RELATIONSHIP
   ------------------------------------------------------------

   Many-to-many relationship between PurePortal research outputs
   and verified Centre researchers.

   The two foreign-key columns together form the composite
   primary key.
*/

CREATE TABLE PUBLICATION_RESEARCHERS (

    PUBLICATION_ID NUMBER
        NOT NULL,

    RESEARCHER_ID NUMBER
        NOT NULL,

    CONSTRAINT PK_PUBLICATION_RESEARCHERS
        PRIMARY KEY (
            PUBLICATION_ID,
            RESEARCHER_ID
        ),

    CONSTRAINT FK_PR_PUBLICATION
        FOREIGN KEY (
            PUBLICATION_ID
        )
        REFERENCES PUBLICATIONS (
            PUBLICATION_ID
        )
        ON DELETE CASCADE,

    CONSTRAINT FK_PR_RESEARCHER
        FOREIGN KEY (
            RESEARCHER_ID
        )
        REFERENCES RESEARCHERS (
            RESEARCHER_ID
        )
        ON DELETE CASCADE
);


/* ------------------------------------------------------------
   TERM INDEX
   ------------------------------------------------------------

   Stores each unique indexed term and its inverse-document-
   frequency value.
*/

CREATE TABLE TERM_INDEX (

    TERM VARCHAR2(255)
        PRIMARY KEY,

    IDF NUMBER
        NOT NULL
);


/* ------------------------------------------------------------
   DOCUMENT TF-IDF VECTORS
   ------------------------------------------------------------

   Stores the sparse processed representation of every indexed
   PurePortal research output.

   VECTOR_JSON contains the document vector in JSON form.
*/

CREATE TABLE DOC_VECTORS (

    URL VARCHAR2(1000)
        PRIMARY KEY,

    TITLE VARCHAR2(1000),

    VECTOR_JSON CLOB
        NOT NULL,

    INDEXED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* ------------------------------------------------------------
   INVERTED INDEX
   ------------------------------------------------------------

   Each posting connects one indexed term with one document and
   stores the term frequency and TF-IDF weight used for retrieval
   and cosine-similarity ranking.
*/

CREATE TABLE INVERTED_INDEX (

    INDEX_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    TERM VARCHAR2(255)
        NOT NULL,

    URL VARCHAR2(1000)
        NOT NULL,

    TERM_FREQUENCY NUMBER
        NOT NULL,

    TF_IDF NUMBER
        NOT NULL
);


/* Improve inverted-index lookup performance. */

CREATE INDEX IDX_INVERTED_TERM
ON INVERTED_INDEX (
    TERM
);


CREATE INDEX IDX_INVERTED_URL
ON INVERTED_INDEX (
    URL
);


/* ============================================================
   TASK 2 - DOCUMENT CLUSTERING
   ============================================================ */


/* ------------------------------------------------------------
   BBC NEWS CLUSTERING DOCUMENTS
   ------------------------------------------------------------

   Stores the fixed source collection used for the clustering task.

   The coursework uses three categories:

       BBC business      -> Economics
       BBC entertainment -> Entertainment
       BBC politics      -> Politics

   SOURCE_CATEGORY preserves the original BBC dataset category.

   COURSEWORK_CATEGORY stores the category terminology used by
   the coursework.

   CLUSTER_ID stores the numerical K-Means cluster assigned after
   clustering.

   User-entered predictions are NOT added to this table. They are
   stored separately in CLUSTER_PREDICTIONS so that prediction
   activity does not modify the original clustering dataset.
*/

CREATE TABLE CLUSTER_DOCUMENTS (

    DOCUMENT_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    DOCUMENT_TEXT CLOB
        NOT NULL,

    SOURCE_CATEGORY VARCHAR2(100)
        NOT NULL,

    COURSEWORK_CATEGORY VARCHAR2(100)
        NOT NULL,

    SOURCE_NAME VARCHAR2(500),

    SOURCE_REFERENCE VARCHAR2(1000),

    CLUSTER_ID NUMBER,

    IMPORTED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* Improve category and cluster filtering. */

CREATE INDEX IDX_CLUSTER_ID
ON CLUSTER_DOCUMENTS (
    CLUSTER_ID
);


CREATE INDEX IDX_COURSEWORK_CATEGORY
ON CLUSTER_DOCUMENTS (
    COURSEWORK_CATEGORY
);


/* ------------------------------------------------------------
   USER PREDICTION HISTORY
   ------------------------------------------------------------

   Stores documents submitted through the Django "Predict Cluster"
   interface.

   Predictions are intentionally separated from CLUSTER_DOCUMENTS
   so they do not alter the original 150-document BBC News dataset
   used for clustering and evaluation.
*/

CREATE TABLE CLUSTER_PREDICTIONS (

    PREDICTION_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    DOCUMENT_TEXT CLOB
        NOT NULL,

    PREDICTED_CLUSTER NUMBER
        NOT NULL,

    PREDICTED_CATEGORY VARCHAR2(100)
        NOT NULL,

    DISTANCE_TO_CENTROID NUMBER(18,10)
        NOT NULL,

    PREDICTED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL
);


/* Newest predictions are frequently displayed first in the UI. */

CREATE INDEX IDX_PREDICTION_TIME
ON CLUSTER_PREDICTIONS (
    PREDICTED_AT
);


/* ============================================================
   OPTIONAL VERIFICATION QUERIES
   ============================================================ */


/*
   ------------------------------------------------------------
   TASK 1 COUNTS
   ------------------------------------------------------------
*/

SELECT COUNT(*) AS RESEARCHERS
FROM RESEARCHERS;


SELECT COUNT(*) AS PUBLICATIONS
FROM PUBLICATIONS;


SELECT COUNT(*) AS PUBLICATION_RESEARCHER_LINKS
FROM PUBLICATION_RESEARCHERS;


SELECT COUNT(*) AS VOCABULARY_TERMS
FROM TERM_INDEX;


SELECT COUNT(*) AS DOCUMENT_VECTORS
FROM DOC_VECTORS;


SELECT COUNT(*) AS INVERTED_INDEX_POSTINGS
FROM INVERTED_INDEX;


/*
   Combined Task 1 index verification.
*/

SELECT

    (SELECT COUNT(*)
     FROM PUBLICATIONS)
        AS PUBLICATIONS,

    (SELECT COUNT(*)
     FROM DOC_VECTORS)
        AS DOCUMENT_VECTORS,

    (SELECT COUNT(*)
     FROM TERM_INDEX)
        AS TERMS,

    (SELECT COUNT(*)
     FROM INVERTED_INDEX)
        AS POSTINGS

FROM DUAL;


/*
   ------------------------------------------------------------
   TASK 1 PUBLICATION METADATA
   ------------------------------------------------------------
*/

SELECT

    COUNT(*) AS TOTAL_PUBLICATIONS,

    SUM(
        CASE
            WHEN PUBLICATION_DATE IS NOT NULL
            THEN 1
            ELSE 0
        END
    ) AS WITH_PUBLICATION_DATE,

    SUM(
        CASE
            WHEN AUTHOR_PROFILES_JSON IS NOT NULL
             AND DBMS_LOB.GETLENGTH(
                    AUTHOR_PROFILES_JSON
                 ) > 2
            THEN 1
            ELSE 0
        END
    ) AS WITH_AUTHOR_PROFILES

FROM PUBLICATIONS;


/*
   Research-output category distribution.
*/

SELECT

    PUBLICATION_TYPE,

    COUNT(*) AS TOTAL

FROM PUBLICATIONS

GROUP BY
    PUBLICATION_TYPE

ORDER BY
    TOTAL DESC,
    PUBLICATION_TYPE;


/*
   ------------------------------------------------------------
   TASK 2 COUNTS
   ------------------------------------------------------------
*/

SELECT COUNT(*) AS CLUSTERING_DOCUMENTS
FROM CLUSTER_DOCUMENTS;


SELECT

    COURSEWORK_CATEGORY,

    COUNT(*) AS DOCUMENTS

FROM CLUSTER_DOCUMENTS

GROUP BY
    COURSEWORK_CATEGORY

ORDER BY
    COURSEWORK_CATEGORY;


/*
   Discovered K-Means cluster composition.
*/

SELECT

    CLUSTER_ID,

    COURSEWORK_CATEGORY,

    COUNT(*) AS DOCUMENTS

FROM CLUSTER_DOCUMENTS

GROUP BY
    CLUSTER_ID,
    COURSEWORK_CATEGORY

ORDER BY
    CLUSTER_ID,
    COURSEWORK_CATEGORY;


/*
   ------------------------------------------------------------
   PREDICTION HISTORY
   ------------------------------------------------------------
*/

SELECT COUNT(*) AS SAVED_PREDICTIONS
FROM CLUSTER_PREDICTIONS;


/*
   Display recent prediction history.

   The Oracle table retains the precise stored timestamp. Django
   converts it to the configured Asia/Kathmandu timezone and formats
   it cleanly for the web interface.
*/

SELECT

    PREDICTION_ID,

    DBMS_LOB.SUBSTR(
        DOCUMENT_TEXT,
        120,
        1
    ) AS DOCUMENT_PREVIEW,

    PREDICTED_CLUSTER,

    PREDICTED_CATEGORY,

    DISTANCE_TO_CENTROID,

    PREDICTED_AT

FROM CLUSTER_PREDICTIONS

ORDER BY
    PREDICTED_AT DESC

FETCH FIRST 10 ROWS ONLY;