/*
    ST7071CEM Information Retrieval Coursework
    Oracle Database Setup Script

    Creates the custom Oracle tables required for:
    Task 1 - Vertical Search Engine
    Task 2 - Document Clustering

    Django framework tables are created separately with:

        python manage.py migrate
*/


/* ============================================================
   TASK 1 - VERTICAL SEARCH ENGINE
   ============================================================ */


/* Verified researchers from the target Coventry University centre. */

CREATE TABLE RESEARCHERS (
    RESEARCHER_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    NAME VARCHAR2(500) NOT NULL,

    PROFILE_URL VARCHAR2(1000)
        NOT NULL
        UNIQUE,

    CENTRE_NAME VARCHAR2(500),

    CRAWLED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* Publications collected and validated by the crawler. */

CREATE TABLE PUBLICATIONS (
    PUBLICATION_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    TITLE VARCHAR2(1000) NOT NULL,

    AUTHORS VARCHAR2(2000),

    PUBLICATION_YEAR NUMBER(4),

    PUBLICATION_URL VARCHAR2(1000)
        NOT NULL
        UNIQUE,

    ABSTRACT CLOB,

    CRAWLED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* Many-to-many relationship between publications and researchers. */

CREATE TABLE PUBLICATION_RESEARCHERS (
    PUBLICATION_ID NUMBER NOT NULL,

    RESEARCHER_ID NUMBER NOT NULL,

    CONSTRAINT PK_PUBLICATION_RESEARCHERS
        PRIMARY KEY (
            PUBLICATION_ID,
            RESEARCHER_ID
        ),

    CONSTRAINT FK_PR_PUBLICATION
        FOREIGN KEY (PUBLICATION_ID)
        REFERENCES PUBLICATIONS(PUBLICATION_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_PR_RESEARCHER
        FOREIGN KEY (RESEARCHER_ID)
        REFERENCES RESEARCHERS(RESEARCHER_ID)
        ON DELETE CASCADE
);


/* Vocabulary and inverse-document-frequency values. */

CREATE TABLE TERM_INDEX (
    TERM VARCHAR2(255)
        PRIMARY KEY,

    IDF NUMBER NOT NULL
);


/* Sparse TF-IDF representation of each publication. */

CREATE TABLE DOC_VECTORS (
    URL VARCHAR2(1000)
        PRIMARY KEY,

    TITLE VARCHAR2(1000),

    VECTOR_JSON CLOB NOT NULL,

    INDEXED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* Term-to-document postings used by the inverted index. */

CREATE TABLE INVERTED_INDEX (
    INDEX_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    TERM VARCHAR2(255) NOT NULL,

    URL VARCHAR2(1000) NOT NULL,

    TERM_FREQUENCY NUMBER NOT NULL,

    TF_IDF NUMBER NOT NULL
);


/* Improve term and URL lookup performance. */

CREATE INDEX IDX_INVERTED_TERM
ON INVERTED_INDEX(TERM);

CREATE INDEX IDX_INVERTED_URL
ON INVERTED_INDEX(URL);


/* ============================================================
   TASK 2 - DOCUMENT CLUSTERING
   ============================================================ */


/*
    BBC News documents used for K-Means clustering.

    SOURCE_CATEGORY preserves the original BBC category.

    Mapping used by the coursework:

        business      -> Economics
        entertainment -> Entertainment
        politics      -> Politics
*/

CREATE TABLE CLUSTER_DOCUMENTS (
    DOCUMENT_ID NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    DOCUMENT_TEXT CLOB NOT NULL,

    SOURCE_CATEGORY VARCHAR2(100)
        NOT NULL,

    COURSEWORK_CATEGORY VARCHAR2(100)
        NOT NULL,

    SOURCE_NAME VARCHAR2(500),

    SOURCE_REFERENCE VARCHAR2(1000),

    CLUSTER_ID NUMBER,

    IMPORTED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
);


/* Improve filtering of cluster results and known categories. */

CREATE INDEX IDX_CLUSTER_ID
ON CLUSTER_DOCUMENTS(CLUSTER_ID);

CREATE INDEX IDX_COURSEWORK_CATEGORY
ON CLUSTER_DOCUMENTS(COURSEWORK_CATEGORY);


/* ============================================================
   OPTIONAL VERIFICATION QUERIES
   ============================================================ */

/*

SELECT COUNT(*) AS RESEARCHERS
FROM RESEARCHERS;

SELECT COUNT(*) AS PUBLICATIONS
FROM PUBLICATIONS;

SELECT COUNT(*) AS PUBLICATION_RESEARCHER_LINKS
FROM PUBLICATION_RESEARCHERS;

SELECT COUNT(*) AS VOCABULARY_TERMS
FROM TERM_INDEX;

SELECT COUNT(*) AS DOCUMENT_VECTORS
FROM DOC_VECTORS;

SELECT COUNT(*) AS INVERTED_INDEX_POSTINGS
FROM INVERTED_INDEX;

SELECT COUNT(*) AS CLUSTERING_DOCUMENTS
FROM CLUSTER_DOCUMENTS;

*/